import AppShell from "@/app/AppShell.jsx";

import '@/styles/cgvSignup.css';
import '@/styles/cgv.css';
import '@/styles/commons.css';
import '@/styles/shoppy.css';
import '@/styles/cart.css';
import '@/styles/checkoutinfo.css';

// import { useAuthStore } from "@/store/authStore.js";
// import AuthHydrator from "@/app/providers/AuthHydrator.js";
// import Header from "@/components/commons/Header.jsx";
// import Footer from "@/components/commons/Footer.jsx";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AppShell>{children}</AppShell> {/* AppShell 컴포넌트는 새로고침(F5) 호출 시 전체 로딩하도록 구현 */}
      {/*  <AuthHydrator />    /!* ← 앱 최초 로딩 시 자동 실행 *!/*/}
      {/*  <Header />*/}
      {/*  {children}*/}
      {/*  <Footer />*/}
      </body>
    </html>
  );
}
